#!/usr/bin/env python2

from os import system

#File to compile
#Output file options
output_name="downloader"

files = "iter_formats.cxx"

#Compiler args
args=" -I/usr/include -I. -lcurl `wx-config --cxxflags --libs`"

#Compiler
compiler="g++"

command = "%s %s -o %s %s" % (compiler, files, output_name, args)

print "Using command: ", command 

system(command)

