#!/usr/bin/env python

from os import system

#File to compile
files="wx-youtube.hpp wx-youtube.cpp MainApp.hpp MainApp.cpp MainFrame.hpp MainFrame.cpp"

#Output file options
output_name="Youtube-wx"

#Compiler args
args="-Wall -lcurl `wx-config --cxxflags --libs`"

#Compiler
compiler="g++"

command = "%s %s -o %s %s" % (compiler, files, output_name, args)

print "Using command: ", command 

system(command)

