#!/usr/bin/env python2

from os import system

#File to compile
#Output file options
output_name="Youtube-wx"

files = "VideoSearch.hpp VideoSearch.cpp Enums.hpp VideoInfo.hpp VideoInfo.cpp SearchURL.hpp SearchURL.cpp DownloadThread.hpp DownloadThread.cpp VideoEntry.hpp VideoEntry.cpp VideoListCtrl.hpp  VideoListCtrl.cpp PrefWindow.hpp PrefWindow.cpp   MainFrame.hpp MainFrame.cpp MainApp.hpp MainApp.cpp"

#Compiler args
args=" -lcurl `wx-config --cxxflags --libs`"

#Compiler
compiler="g++"

command = "%s %s -o %s %s" % (compiler, files, output_name, args)

print "Using command: ", command 

system(command)

