#!/usr/bin/env python2

from os import system

#File to compile
files = "wx-youtube.hpp wx-youtube.cpp Enums.hpp VideoInfo.hpp VideoInfo.cpp SearchURL.hpp SearchURL.cpp DownloadThread.hpp DownloadThread.cpp VideoEntry.hpp VideoEntry.cpp VideoListCtrl.hpp  VideoListCtrl.cpp PrefWindow.hpp PrefWindow.cpp   MainFrame.hpp MainFrame.cpp MainApp.hpp MainApp.cpp -o Youtube-wx  -lcurl `wx-config --cxxflags --libs`"
#Output file options
output_name="Youtube-wx"

#Compiler args
args=" -lcurl `wx-config --cxxflags --libs`"

#Compiler
compiler="g++"

command = "%s %s -o %s %s" % (compiler, files, output_name, args)

print "Using command: ", command 

system(command)

