#!/usr/bin/env python

from os import system

#File to compile
file="iterate_user_videos.cxx"

#Output file options
output_name="iterate_videos"

#Compiler args
args=" `curl-config --cflags` `curl-config --libs`"

#Compiler
compiler="g++"

command = "%s %s -o %s %s" % (compiler, file, output_name, args)

#print "Using command: ", command 

system(command)
